# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Nmap-Parser-XML
version:      0.73
version_from: XML.pm
installdirs:  site
requires:
    XML::Twig:                     3.09

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
